### ISSUE TITLE
文章标题应大写以与官网保持一致

### ISSUE THREAD

**Issue by Olvcpr423** [SPXFellow/spxx#1]
官网文章的标题虽然实质上（通过审查元素可见）是形如“Taking Inventory: Blaze Powder”的首字母大写形式，但实际渲染显示效果却是全大写形式，如“TAKING INVENTORY： BLAZE POWDER”。建议在转换成 BBCode 时使用全大写标题形式，以求帖子之观感与官网相一致。

**Comment by RicoloveFeng** [comment]
我想过，但是我认为title格式比all cap要好看。dlldd怎么说？ @Dianliang233

**Comment by Dianliang233** [comment]
都行吧

**Comment by Dianliang233** [comment]
我是觉得可能 all caps 可能会降低可读性

**Comment by RicoloveFeng** [comment]
> 我是觉得可能 all caps 可能会降低可读性

那discord投个票好了

**Comment by Dianliang233** [comment]
结果是 all caps

**Comment by RicoloveFeng** [comment]
那改一下好了，顺便更新模板

**Comment by Dianliang233** [comment]
discord webhook test
